In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import numpy as np
import math
import os

In [2]:
spectral_dict = {
    'UVA': {'wavelength': 365, 'file': ''},
    'Violet': {'wavelength': 405, 'file': ''},
    'Indigo': {'wavelength': 430, 'file': ''},
    'Blue_1': {'wavelength': 450, 'file': ''},
    'Blue_2': {'wavelength': 470, 'file': ''},
    'Azure': {'wavelength': 490, 'file': ''},
    'Cyan': {'wavelength': 515, 'file': ''},
    'Green': {'wavelength': 540, 'file': ''},
    'Yellow': {'wavelength': 570, 'file': ''},
    'Amber': {'wavelength': 590, 'file': ''},
    'Red_1': {'wavelength': 630, 'file': ''},
    'Red_2': {'wavelength': 645, 'file': ''},
    'Red_3': {'wavelength': 660, 'file': ''},
    'Red_4': {'wavelength': 690, 'file': ''},
    'NIR_1': {'wavelength': 780, 'file': ''},
    'NIR_2': {'wavelength': 850, 'file': ''},
    'NIR_3': {'wavelength': 880, 'file': ''},
    'NIR_4': {'wavelength': 940, 'file': ''},
    'NIR_5': {'wavelength': 970, 'file': ''}
}

In [3]:
df = pd.read_csv(r"VideoMeter_lights_off\capture00000.txt",
                 sep='\t', header=None, names=['spectro', 'intensity'])

df

      spectro intensity
0      344,25   1247,21
1      344,46   1247,21
2      344,68   1247,21
3      344,90   1310,70
4      345,12   1267,69
...       ...       ...
3643  1042,27   1417,19
3644  1042,43   1488,87
3645  1042,59   1452,01
3646  1042,75   1447,91
3647  1042,91   1464,30

[3648 rows x 2 columns]

In [4]:
# Transformar a coluna spectro em inteiros para coincidir com as chaves do dicionário
df['spectro'] = df['spectro'].str.replace(',', '.')
df['spectro'] = pd.to_numeric(df['spectro'], errors='coerce')  # float
df['spectro'] = df['spectro'].round().astype('Int64')
df

      spectro intensity
0         344   1247,21
1         344   1247,21
2         345   1247,21
3         345   1310,70
4         345   1267,69
...       ...       ...
3643     1042   1417,19
3644     1042   1488,87
3645     1043   1452,01
3646     1043   1447,91
3647     1043   1464,30

[3648 rows x 2 columns]

# Lights ON

In [5]:
folder_path = 'VideoMeter_lights_on'

In [ ]:
for name, spectro in spectral_dict.items():

    files = [os.path.join(folder_path, nome) for nome in os.listdir(folder_path)]

    aux_dict = {}
    for file in files:
      df = pd.read_csv(file, sep='\t', header=None, names=['spectro', 'intensity'])

      # Transformar a coluna spectro em inteiros para coincidir com as chaves do dicionário
      df = df.replace(',', '.', regex=True)
      df = df.apply(pd.to_numeric, errors='coerce')
      df['spectro'] = df['spectro'].round().astype('Int64')

      df_filtered = df[df['spectro'] == spectro['wavelength']]
      aux_dict[file] = round(df_filtered['intensity'].mean(), 3)

    max_file = max(aux_dict, key=aux_dict.get)
    max_value = aux_dict[max_file]

    print(f'{name}: biggest intensity = {max_value} in the file {os.path.basename(max_file)}')
    spectral_dict[name]['file'] = os.path.basename(max_file)

UVA: maior intensidade = 4343.742 no arquivo capture00046.txt
Violet: maior intensidade = 1786.648 no arquivo capture00085.txt
Indigo: maior intensidade = 1829.246 no arquivo capture00105.txt
Blue_1: maior intensidade = 1803.854 no arquivo capture00087.txt
Blue_2: maior intensidade = 2497.292 no arquivo capture00069.txt
Azure: maior intensidade = 3097.758 no arquivo capture00070.txt
Cyan: maior intensidade = 4936.016 no arquivo capture00110.txt
Green: maior intensidade = 2476.814 no arquivo capture00186.txt
Yellow: maior intensidade = 5059.71 no arquivo capture00054.txt
Amber: maior intensidade = 3222.684 no arquivo capture00169.txt
Red_1: maior intensidade = 5161.29 no arquivo capture00000.txt
Red_2: maior intensidade = 3945.206 no arquivo capture00076.txt
Red_3: maior intensidade = 3292.452 no arquivo capture00039.txt
Red_4: maior intensidade = 2394.076 no arquivo capture00116.txt
NIR_1: maior intensidade = 2059.848 no arquivo capture00079.txt
NIR_2: maior intensidade = 1861.945 no arquivo capture00195.txt
NIR_3: maior intensidade = 1700.837 no arquivo capture00100.txt
NIR_4: maior intensidade = 1685.818 no arquivo capture00045.txt
NIR_5: maior intensidade = 1547.922 no arquivo capture00197.txt

In [7]:
spectral_dict

{'UVA': {'wavelength': 365, 'file': 'capture00046.txt'},
 'Violet': {'wavelength': 405, 'file': 'capture00085.txt'},
 'Indigo': {'wavelength': 430, 'file': 'capture00105.txt'},
 'Blue_1': {'wavelength': 450, 'file': 'capture00087.txt'},
 'Blue_2': {'wavelength': 470, 'file': 'capture00069.txt'},
 'Azure': {'wavelength': 490, 'file': 'capture00070.txt'},
 'Cyan': {'wavelength': 515, 'file': 'capture00110.txt'},
 'Green': {'wavelength': 540, 'file': 'capture00186.txt'},
 'Yellow': {'wavelength': 570, 'file': 'capture00054.txt'},
 'Amber': {'wavelength': 590, 'file': 'capture00169.txt'},
 'Red_1': {'wavelength': 630, 'file': 'capture00000.txt'},
 'Red_2': {'wavelength': 645, 'file': 'capture00076.txt'},
 'Red_3': {'wavelength': 660, 'file': 'capture00039.txt'},
 'Red_4': {'wavelength': 690, 'file': 'capture00116.txt'},
 'NIR_1': {'wavelength': 780, 'file': 'capture00079.txt'},
 'NIR_2': {'wavelength': 850, 'file': 'capture00195.txt'},
 'NIR_3': {'wavelength': 880, 'file': 'capture00100.txt'},
 'NIR_4': {'wavelength': 940, 'file': 'capture00045.txt'},
 'NIR_5': {'wavelength': 970, 'file': 'capture00197.txt'}}

In [ ]:
# Corresponds to blue_2 wavelenght biggest intensity
file_to_plot = "VideoMeter_lights_on/capture00069.txt"


df_plot = pd.read_csv(file_to_plot, sep='\t', header=None, names=['spectro', 'intensity'])
df_plot = df_plot.replace(',', '.', regex=True)
df_plot = df_plot.apply(pd.to_numeric, errors='coerce')

fig = px.line(df_plot, x='spectro', y='intensity', title=f'Intensity vs Wavelength for {os.path.basename(file_to_plot)}')
fig.update_layout(
    xaxis_title='Wavelength (spectro)',
    yaxis_title='Intensity',
    hovermode='x unified' # Optional: show tooltips for all lines at a given x-value
)

pio.renderers.default = "notebook_connected"
fig.show()

# Lights OFF

In [10]:
folder_path = 'VideoMeter_lights_off'

In [11]:
for name, spectro in spectral_dict.items():

    files = [os.path.join(folder_path, nome) for nome in os.listdir(folder_path)]

    aux_dict = {}
    for file in files:
      df = pd.read_csv(file, sep='\t', header=None, names=['spectro', 'intensity'])

      # Transformar a coluna spectro em inteiros para coincidir com as chaves do dicionário
      df = df.replace(',', '.', regex=True)
      df = df.apply(pd.to_numeric, errors='coerce')
      df['spectro'] = df['spectro'].round().astype('Int64')

      df_filtered = df[df['spectro'] == spectro['wavelength']]
      aux_dict[file] = round(df_filtered['intensity'].mean(), 3)

    max_file = max(aux_dict, key=aux_dict.get)
    max_value = aux_dict[max_file]

    print(f'{name}: biggest intensity = {max_value} in the file {os.path.basename(max_file)}')
    spectral_dict[name]['file'] = os.path.basename(max_file)

UVA: biggest intensity = 4375.995 in the file capture00066.txt
Violet: biggest intensity = 1803.85 in the file capture00086.txt
Indigo: biggest intensity = 1821.464 in the file capture00030.txt
Blue_1: biggest intensity = 1833.75 in the file capture00164.txt
Blue_2: biggest intensity = 2488.282 in the file capture00241.txt
Azure: biggest intensity = 3131.754 in the file capture00128.txt
Cyan: biggest intensity = 4936.426 in the file capture00035.txt
Green: biggest intensity = 2489.51 in the file capture00168.txt
Yellow: biggest intensity = 5074.046 in the file capture00112.txt
Amber: biggest intensity = 3209.166 in the file capture00189.txt
Red_1: biggest intensity = 4791.016 in the file capture00302.txt
Red_2: biggest intensity = 3926.366 in the file capture00172.txt
Red_3: biggest intensity = 3302.008 in the file capture00002.txt
Red_4: biggest intensity = 2404.316 in the file capture00231.txt
NIR_1: biggest intensity = 2079.1 in the file capture00194.txt
NIR_2: biggest intensity = 1873.89 in the file capture00289.txt
NIR_3: biggest intensity = 1730.533 in the file capture00234.txt
NIR_4: biggest intensity = 1721.66 in the file capture00084.txt
NIR_5: biggest intensity = 1547.242 in the file capture00141.txt

In [12]:
spectral_dict

{'UVA': {'wavelength': 365, 'file': 'capture00066.txt'},
 'Violet': {'wavelength': 405, 'file': 'capture00086.txt'},
 'Indigo': {'wavelength': 430, 'file': 'capture00030.txt'},
 'Blue_1': {'wavelength': 450, 'file': 'capture00164.txt'},
 'Blue_2': {'wavelength': 470, 'file': 'capture00241.txt'},
 'Azure': {'wavelength': 490, 'file': 'capture00128.txt'},
 'Cyan': {'wavelength': 515, 'file': 'capture00035.txt'},
 'Green': {'wavelength': 540, 'file': 'capture00168.txt'},
 'Yellow': {'wavelength': 570, 'file': 'capture00112.txt'},
 'Amber': {'wavelength': 590, 'file': 'capture00189.txt'},
 'Red_1': {'wavelength': 630, 'file': 'capture00302.txt'},
 'Red_2': {'wavelength': 645, 'file': 'capture00172.txt'},
 'Red_3': {'wavelength': 660, 'file': 'capture00002.txt'},
 'Red_4': {'wavelength': 690, 'file': 'capture00231.txt'},
 'NIR_1': {'wavelength': 780, 'file': 'capture00194.txt'},
 'NIR_2': {'wavelength': 850, 'file': 'capture00289.txt'},
 'NIR_3': {'wavelength': 880, 'file': 'capture00234.txt'},
 'NIR_4': {'wavelength': 940, 'file': 'capture00084.txt'},
 'NIR_5': {'wavelength': 970, 'file': 'capture00141.txt'}}

In [17]:
# Corresponds to blue_2 wavelenght biggest intensity
file_to_plot = "VideoMeter_lights_off/capture00241.txt"


df_plot = pd.read_csv(file_to_plot, sep='\t', header=None, names=['spectro', 'intensity'])
df_plot = df_plot.replace(',', '.', regex=True)
df_plot = df_plot.apply(pd.to_numeric, errors='coerce')

fig = px.line(df_plot, x='spectro', y='intensity', title=f'Intensity vs Wavelength for {os.path.basename(file_to_plot)}')
fig.update_layout(
    xaxis_title='Wavelength (spectro)',
    yaxis_title='Intensity',
    hovermode='x unified' # Optional: show tooltips for all lines at a given x-value
)

pio.renderers.default = "notebook_connected"
fig.show()